# Generated by Django 3.2.7 on 2021-11-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='copper',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='iron',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='nitrogen',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='phosphorus',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='potassium',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='zinc',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
