# Generated by Django 3.2.7 on 2021-11-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_auto_20211102_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='village',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
